python train.py \
    -project mine \
    -dataset in1k_fscil \
    -dataroot /home/zongyao/Dataset/ImageNet1K/imagenet_fscil_benchmark_800base \
    -base_mode ft_cos \
    -new_mode avg_cos \
    -gamma 0.25 \
    -lr_base 0.004 \
    -lr_new 0.1 \
    -decay 0.0005 \
    -epochs_base 0 \
    -schedule Milestone \
    -milestones 50 100 150 200 250 300 \
    -gpu 4 \
    -temperature 4 \
    -batch_size_base 256 \
    -test_batch_size 256 \
    -softmax_t 16 \
    -shift_weight 0.5 \
    -num_workers 8 \
    -shot 5 \
    -soft_mode no_calibration 
